
spring:
#  database connection
  datasource:
    driver-class-name: dummy
    url: dummy
    username: dummy
    password: dummy

# file upload
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 100MB
#mybatis
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

#aws
aws:
  endpointUrl: dummy
  accessKey: dummy
  secretKey: dummy
  bucketName: dummy
  region: dummy

#spring transaction control
logging:
  level:
    org.springframework.jdbc.support.JdbcTransactionManager: debug


