
spring:
#  database connection
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://aws.connect.psdb.cloud/jl_practice?sslMode=VERIFY_IDENTITY
    username: ql0pne6xvr0tfqwo965j
    password: pscale_pw_w1ZiQoQBG75E89aH6dpXMnID708COn7iUgTIU1W7Kw9
# file upload
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 100MB
#mybatis
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

#aws
aws:
  endpointUrl: https://s3.cloudLocation.amazonaws.com
  accessKey: AKIAYDBZD4PQC75O35QL
  secretKey: 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
  bucketName: springbootbucket-practice
  region: us-east-2

#spring transaction control
logging:
  level:
    org.springframework.jdbc.support.JdbcTransactionManager: debug


